import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import Providers from "@/store/provider"
import Carrito from "./carrito/Carrito"

const fuente = Montserrat({
  weight: '400',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Providers>
        <body className={fuente.className}>
          <Carrito />
          <div>{children}</div>
        </body>
      </Providers>

    </html>
  )
}
